from langchain_groq import ChatGroq
from langchain_community.tools.tavily_search import TavilySearchResults
from langgraph.prebuilt import create_react_agent
from app.common.logger import get_logger
from langchain_core.messages import AIMessage

from app.config.settings import settings

logger = get_logger(__name__)
def get_response_from_ai_agents(llm_id, query, allow_search:bool, system_prompt):
    logger.info('Enter')
    llm = ChatGroq(model = llm_id)
    #if web search is allowed, fetch only the top 2 search from the internet search results returned by tavily
    tools = [TavilySearchResults(max_result=2)] if allow_search else []

    agent = create_react_agent(model=llm, tools=tools, prompt=system_prompt)
    state = {'messages':query}
    response = agent.invoke(state)#ask the agent the question
    
    messages = response.get('messages')
    logger.info(f'AI Agent response: {messages}')
    ai_response = [message.content for message in messages if isinstance(message, AIMessage)]# get only the AIMessage from the response
    logger.info('Exit')
    return ai_response[-1]#get the last message generated by the AI








